import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import NavBar from "./components/navBAr/navBar";
export const metadata = {
  title: "Data wheel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <NavBar />
        
        
        {children}</body>
    </html>
  );
}
